### ISSUE TITLE
Compatible with esp8266?

### ISSUE THREAD

**Issue by vkhurana** [TomVickers/Arduino2keypad#1]
Hey Tom,

Great repo! I was looking at building something similar, and came across yours and Mark Kimsal's work.

I was just wondering if you have experimented with an esp8266 as an arduino replacement.

There's a few reasons I bring this up:
- The wifi on the ESP can be used for direct RX/TX with an automation software (HomeAssistant?)
- eliminate the need for a companion pi

Best

**Comment by TomVickers** [comment]
Hi.  Thanks for the feedback.  I have done an esp8266 project before and it would have probably been fine for this task.  However, I was always planning to use the RPi as my main alarm processor (with a few other home automation tasks).  As the RPi is already handling my Wifi interface, I did not think about using the esp8266 for this part of the project.  In truth, I hoped to be able handle the whole project with just the RPi.  But it became clear to me that a small micro would be the best way to handle the funky serial interface of the Honeywell keypads.

Also, the entire project is mounted in the original steel alarm enclosure from the Honeywell alarm.  I use a USB wifi dongle with an external antenna that is through hole mounted, so it can receive wifi with the box closed up.  Are there esp8266 external antenna solutions?

**Comment by vkhurana** [comment]
Great! I'll look at doing this using an ESP8266, for my system. The idea I have is to have the ESP listen to events, and report them to HomeAssistant over MQTT, exposing them as sensors to the system.

Yes, I believe the ESP does have a variant that can work with an external antenna - The Wemos D1 Mini PRO. I haven't tested it myself, but i've seen a few projects that use it (ex: https://github.com/aderusha/MQTTCarPresence)
