### ISSUE TITLE
Parts list?

### ISSUE THREAD

**Issue by brianegge** [TomVickers/Arduino2keypad#2]
Do you have a parts list for the Arduino board? Do you have any interest in selling an assembled hat with flashed Arduino?

**Comment by TomVickers** [comment]
I can provide you a parts list. I am not really interested in building the
hat, but I can send you a compiled file for the Arduino. Loading is pretty
easy, just need a serial cable. I will get it to you this weekend.

Tom

**Comment by TomVickers** [comment]
Hi Brian,

I hope this helps.  A more detailed parts list (with links) is below.  I
have also attached an updated schematic (with the part labels) and a
picture of how I assembled my perf board.  I already had some perf board,
but something like this would work too (
https://www.amazon.com/HiLetgo-Finished-Prototype-Circuit-Breadboard/dp/B07BPY8KJG).
I built my circuit on a small breadboard first and made sure it was working
with my keypad.  Then I transferred the parts to the perfboard.

I used male header pins like this (
https://www.amazon.com/DEPEPE-2-54mm-Headers-Arduino-Prototype/dp/B074HVBTZ4)
to connect the perf board to the Arduino.

I used a 4-pin terminal block like this (
https://www.amazon.com/uxcell-Terminal-Block-Connector-5-0mm/dp/B013FJOU5S)
on my hat for the wire connections to the keypad.

You may notice some extra parts on the hat in my photograph on github.
These parts are not required to talk to the keypad.  I put some extra parts
on to make it easier to connect my logic analyzer.  I can provide details
of that if you are trying to connect a logic analyzer to your setup.

<snip>
The rest of this (a table and some attached images), Github didn't like.  I sent it to your gmail account.  Let me know if you didn't get it.

**Comment by TomVickers** [comment]
I am closing this issue as addressed. Let me know if you have any more questions.
