### ISSUE TITLE
Bitmap of open zones? 

### ISSUE THREAD

**Issue by alanrothenbush** [TomVickers/Arduino2keypad#3]
Forgive me this backhanded way of contacting you, but I have a question and this is the only way I could think of. 

The short version of the question is this:  Does a Honeywell panel send a list of open zones to a keypad?

Here's the long version.  I have a lot of zones in my house .. a lot.  I have contacts on all the doors and windows as well as the locks.  (Big deal that the door is closed, is it locked?) 

Problem 1 is that I have "dumb" keypads at the doors.  They don't say "Garage open", they say "17", which means I also have a list of names and numbers on a piece of paper by the panels. 

Problem 2 is that on a summer day, all the doors and windows are open and so my keypads spend a minute or more telling me about, as they slowly flash the open zone numbers.  11  17  13  34  4  5  9  and so on (and on and on).  I can go close something and then have to wait a long time before I know it's closed.  Worse, I have to remember what number it was that was closed and then wait long enough to convince myself that it's no longer in the list.

This is, quite frankly, insane, as user unfriendly as can be.  DSC keypads tell you instantly that a zone is OK.  The supposedly "better" Honeywell system does not.

Anyway, my plan for item 1 was an Arduino and an LCD.  When the Arduino saw an F7 message with "FAULT 17" in it, the LCD would display "Garage Unlocked"

This works fine; there's just a big lookup table of fault codes and names; easy.

But problem 2 remains, the potentially LONG time before knowing that a zone is no longer open.

I was wondering if you have any reason to believe that the panel sends open zone information to the bus/keypad as a single complete message?  Maybe those unknown bytes are bitmaps of zone status?

Thanks for any thoughts.

**Comment by TomVickers** [comment]
Hi Alan,

My direct email is ***@***.*** if that helps.

I did not spend much time trying to figure out the Honeywell alarm as I
removed it and replaced it with a Raspberry PI.  I did want to retain the
keypads at the doors, so I spent some time with a logic analyzer hooked up
to the panel wires to figure out the protocol.  I wrote up what I figured
out in a doc on my github site.  There are certainly other mysteries to be
solved, but I learned enough to make my system work the way I wanted it to.

I am happy to help if I can, but I am not sure I have the info you are
looking for.

Thanks,
Tom

**Comment by TomVickers** [comment]
whoops... github stripped my email.  Maybe this will work: thomas(dot)e(dot)vickers(at)gmail(dot)com

**Comment by TomVickers** [comment]
You might also want to look at the github site I reference in my README, 

http://getatanc.com/ and github repository https://github.com/TANC-security/keypad-firmware 

He was trying to create his own alarm panel for communicating with the Honeywell alarm (which sounds similar to what you are doing).  I used info he had the other way (to talk to my LCD keypad from the Arduino)

**Comment by alanrothenbush** [comment]
Thanks!
